# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: Default

steps:
- script: |
    echo $(SUDO_PASSWORD) | sudo -S rm -rf /var/www/website
    echo $(SUDO_PASSWORD) | sudo -S mkdir /var/www/website
  displayName: File Cleanup
- script: |
    cd ui
    yarn install
    wget https://gist.githubusercontent.com/a1g3/64995f47f95365bf4fa41c0d81061f96/raw/06fba957888d151ff0edc49cb1bde36cdc76e5dc/index.d.ts
    mv index.d.ts node_modules/react-split/
    export REACT_APP_BASE_API_URL=https://tabot.sh
    yarn run build
    echo $(SUDO_PASSWORD) | sudo -S mv build /var/www/website
  displayName: 'Install frontend'
