# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: Default
steps:
- script: |
    echo $(SUDO_PASSWORD) | sudo -S sudo service gunicorn stop
  displayName: 'Stop web server'
- script: |
    echo $(SUDO_PASSWORD) | sudo -S rm -rf /var/www/api/
    sudo mv $(Build.Repository.LocalPath)/api /var/www/
    sudo rm /var/www/api/app.py
    sudo mv /var/www/api/app-prod.py /var/www/api/app.py
    sudo rm /var/www/api/src/repositories/database.py
    sudo mv /var/www/api/src/repositories/database-prod.py /var/www/api/src/repositories/database.py
    sudo chown -R www-data:www-data /var/www/api
  displayName: 'Update api folder'
- script: |
    echo $(SUDO_PASSWORD) | sudo -S service gunicorn restart
  displayName: 'Start web server'

