# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool: Default
steps:
- script: |
    echo $(SUDO_PASSWORD) | sudo -S sudo service gunicorn stop
  displayName: 'Stopping web server'
- script: |
    echo $(SUDO_PASSWORD) | sudo -S rm -rf /home/agebhard/AutoTA/api/
    sudo mv $(Build.Repository.LocalPath)/api /home/agebhard/AutoTA/
  displayName: 'Updating api folder'
- script: |
    echo $(SUDO_PASSWORD) | sudo -S service gunicorn restart
  displayName: 'Starting web server'

