# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- output-research

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- script: |
    cd $(Build.SourcesDirectory)/ui
    yarn install
    wget https://gist.githubusercontent.com/a1g3/64995f47f95365bf4fa41c0d81061f96/raw/06fba957888d151ff0edc49cb1bde36cdc76e5dc/index.d.ts
    mv index.d.ts node_modules/react-split/
    yarn run build
    cp -R build/ $(Build.ArtifactStagingDirectory)
  displayName: 'Install frontend'
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: drop