# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global yarn
  displayName: 'Install Yarn'

- script: |
    cd ui/
    yarn install
    wget https://gist.githubusercontent.com/a1g3/64995f47f95365bf4fa41c0d81061f96/raw/06fba957888d151ff0edc49cb1bde36cdc76e5dc/index.d.ts
    mv index.d.ts node_modules/react-split/
  displayName: 'Install Yarn and packages'

- script: |
    cd ui/
    yarn run build
  displayName: 'Build website'

- script: |
    mv ui/build/ $(Build.ArtifactStagingDirectory)
  displayName: 'Upload website'
