version: "3.8"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'autota'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./database:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: api
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    container_name: frontend
    restart: unless-stopped
    environment:
      REACT_APP_BASE_API_URL: http://localhost:5000/api
    build:
      context: ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
