# Pull node base image
FROM node:14 as build

# set working directory
WORKDIR /app

# Install depenencies
COPY package.json .
COPY yarn.lock .
RUN yarn install 
RUN yarn global add react-scripts --silent

# Add app
COPY . .

# production environment
FROM build as production

# add `/app/node_modules/.bin` to PATH
ENV PATH /app/node_modules/.bin:$PATH

# build app
RUN yarn build

EXPOSE 3000

# start app
CMD ["node", "/app/build/server.js"]
