FROM python:3.10-slim-bookworm

# set working directory
WORKDIR /app

# set timezone
ENV TZ=America/Chicago

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt
RUN pip install requests
RUN pip install pylint
RUN pip install --upgrade openai
RUN pip install aiopyston
RUN pip install gunicorn

# copy every content from the local file to the image
COPY . /app

ENV FLASK_APP=app.py
ENV FLASK_DEBUG=False

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:create_app()"]
